Resolve 'Android SDK update & macOS/iOS contact bug'
skalio/flutter-addressbook-mobile pull request #6
Opened 2022-11-24 12:51 UTC by leonx98

* plugin is now working with newest Android SDK (33)
* fix bug where only contacts with telephone numbers are returned (macOS/iOS)

2022-11-24 13:01 UTC, jagmit requested changes

2022-11-24 13:01 UTC, jagmit commented on README.md
> +* Android 4
```suggestion
* Android 4.0+
```
Are you sure we are compatible with ice cream sandwich which was released 11 years ago?

2022-11-24 13:51 UTC, leonx98 commented on README.md
> +* Android 4
I didn't change the `minSdkVersion`. It's set to 16 which means in my Android understanding that everything from `Jelly Bean` is compatible. So `Ice Cream Sandwich` would not be working.

2022-11-25 13:00 UTC, technolion approved these changes
LGTM!

2022-11-25 13:00 UTC, merged